language: cpp
dist: xenial
compiler: gcc

install:

 # Qt5
 - sudo apt-get install -qq qt5-qmake qt5-default

script: 
  
 # Build and run and profile normal program
 - qmake ./program.pro
 - make --silent release
